# https://www.docker.elastic.co/
FROM elasticsearch:7.7.0

# Add your elasticsearch plugins setup here, e.g.:
# RUN elasticsearch-plugin install analysis-icu

COPY config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml