---
# Deploy web applications

- hosts: local
  user: www-data
  become: no
  vars:
    - webapp_path: "~/workspace/projects/devops/webapp"
    - webapp_list:
      - image_name: "flask-info"
        version: "v1.0"
        container_name: "flask-info"
        links: ["my-db:db", "my-redis:redis"]
        ports: "5500:5000"  #host port 5000 is reserved for logstash
        state: "started"
    - dev_server: {name: dev-server,
                  image: "my-server:latest",
                  ports: ["80:10080"],
                  links: ["my-db:db", "my-redis:redis"],
                  volumes: ["~/workspace/projects/devops/www:/var/www/sites"]
                  }

  tasks:
    # - build webapp docker images
    - name: Build webapp images
      docker_image:
        build:
          path: "{{webapp_path}}/{{ item.directory|default(item.image_name) }}"
          pull: yes
        source: build
        name: "{{ item.image_name }}"
        tag: "{{ item.version }}"
        state: present
      with_items: "{{webapp_list}}"

    # - deploy webapp docker containers
    - name: Build webapp containers
      docker_container:
        image: "{{ item.image_name }}:{{ item.version }}"
        name: "{{ item.container_name }}"
        links: "{{ item.links }}"
        ports: "{{ item.ports }}"
        state: "{{ item.state }}"
      with_items: "{{webapp_list}}"

    # Create a development web server
    # docker run --name dev-server my-server:latest
    - name: Create a develop web server container
      docker_container:
        image: "{{ dev_server.image }}"
        name: "{{ dev_server.name }}"
        links: "{{ dev_server.links }}"
        volumes: "{{ dev_server.volumes }}"
        ports: "{{ dev_server.ports }}"
        state: started
        user: www-data