# Build a data volume
FROM busybox

LABEL Maintainer="Bill Yang <bill.yang@live.ca>" Description="Data volume docker based on busybox."

# data volume for MySQL.
RUN mkdir -p /var/lib/mysql
VOLUME /var/lib/mysql
